name:                gpu-vulkan-khr-swapchain
version:             0.1.0.0
github:              "YoshikuniJujo/gpu-vulkan-khr-swapchain"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "Copyright (c) 2023 Yoshikuni Jujo"

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            VK_KHR_swapchain extension of the Vulkan API
category:            GPU

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/gpu-vulkan-khr-swapchain#readme>

dependencies:
- base >= 4.7 && < 5
- stm < 3
- containers < 1
- gpu-vulkan < 1
- gpu-vulkan-khr-surface < 1
- gpu-vulkan-middle-khr-swapchain < 1
- storable-peek-poke < 1
- hetero-parameter-list < 1
- fixed-generic < 1
- typelevel-tools-yj < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Gpu.Vulkan.Khr.Swapchain

tests:
  gpu-vulkan-khr-swapchain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpu-vulkan-khr-swapchain
